export enum NewsCategory {
    CULTURE = 'CULTURE',
    ECONOMICS = 'ECONOMICS',
    INCIDENTS = 'INCIDENTS',
    POLITICS = 'POLITICS',
    SCIENCE = 'SCIENCE',
    SOCIETY = 'SOCIETY',
    TECHNOLOGIES = 'TECHNOLOGIES',
    TRANSPORT = 'TRANSPORT'
}
